//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProFin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etkilesim
    {
        public int EtkilesimID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string EtkilesimTuru { get; set; }
        public string Detay { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Projeler Projeler { get; set; }
    }
}
