//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProFin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faturalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faturalar()
        {
            this.FaturaKalemleri = new HashSet<FaturaKalemleri>();
        }
    
        public int FaturaID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public string FaturaNumarasi { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<int> KDVOrani { get; set; }
        public string OdemeDurumu { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string DurumBilgi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaKalemleri> FaturaKalemleri { get; set; }
        public virtual Musteriler Musteriler { get; set; }
        public virtual Projeler Projeler { get; set; }
    }
}
