//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProFin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giderler
    {
        public int GiderID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Kategori { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> OdemeDurumu { get; set; }
    }
}
