//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProFin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raporlar
    {
        public int RaporID { get; set; }
        public string RaporAdi { get; set; }
        public Nullable<int> OlusturanKullaniciID { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public string RaporDetaylari { get; set; }
    }
}
